export const SET_FETCHING = 'SET_FETCHING';
export const SET_BUILD_LIST = 'SET_BUILD_LIST';
export const SET_BUILD_LOGS = 'SET_BUILD_LOGS';
export const SET_COUNT_LOADED_BUILDS = 'SET_COUNT_LOADED_BUILDS';
export const SET_SETTINGS = 'SET_SETTINGS';
